apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomizegoat
  namespace: kustomizegoat
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10014
        runAsGroup: 10014
      containers:
        securityContext:
          allowPrivilegeEscalation: false
